beebloge/blogPosts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField
from flask_wtf.file import FileField, FileAllowed


class BlogPostForm(FlaskForm):
    title           = StringField('Tytuł'       , validators=[DataRequired()])
    category        = StringField('Kategoria'   , validators=[DataRequired()])
    text            = CKEditorField('Text'      , validators=[DataRequired()])
    picture         = FileField('Grafika'       , validators=[FileAllowed(['jpg', 'png'])])
    submit          = SubmitField('Opublikuj')

beebloge/blogPosts/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from flask_security import current_user
from beebloge import db
from beebloge.models import BlogPost, Comment
from beebloge.users.picture_handler import add_pic, del_pic
from beebloge.users.views import requires_roles
from beebloge.blogPosts.forms import BlogPostForm
from beebloge.comments.forms import CommentForm

blog_posts = Blueprint('blogPosts', __name__)


@blog_posts.route('/create/post', methods=['GET', 'POST'])
@login_required
@requires_roles('admin')
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        if form.picture.data:
            imgname = "".join([form.title.data[:10], form.category.data])
            pic = add_pic(form.picture.data, imgname, 'post_pics', (600, 600))

            blog_post = BlogPost(title      =form.title.data,
                                 text       =form.text.data,
                                 category   =form.category.data,
                                 user_id    =current_user.id,
                                 post_image =pic)
        # flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('addPost.html', form=form)


@blog_posts.route('/post/<int:blog_post_id>', methods=["GET", "POST"])
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body          =form.comment.data,
                          product_id    =None,
                          post_id       =blog_post.id,
                          user_id       =current_user.id)
        db.session.add(comment)
        db.session.commit()
        # flash("Your comments has been added to the post", "success")

    return render_template('blogPost.html',
                           title        =blog_post.title,
                           date         =blog_post.date,
                           post         =blog_post,
                           category     =blog_post.category,
                           post_image   =blog_post.post_image,
                           form         =form
                           )


@blog_posts.route('/post/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)
    form = BlogPostForm()
    if form.picture.data:
        imgname = "".join([form.title.data, form.category.data])
        pic = add_pic(form.picture.data, imgname, 'post_pics', (800, 800))
        blog_post.post_image = pic
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        blog_post.category = form.category.data
        db.session.commit()
        # flash('Post Updated')
        return redirect(url_for('blogPosts.blog_post',
                                blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
        form.category.data = blog_post.category
        form.picture.data = blog_post.post_image
    return render_template('addPost.html',
                           title='Update',
                           form=form)


@blog_posts.route('/post/<int:blog_post_id>/delete', methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    del_pic(folder_name='post_pics', fileName=blog_post.post_image)
    db.session.delete(blog_post)
    db.session.commit()
    # flash('Post has been deleted')
    return redirect(url_for('core.index'))

beebloge/comments/views.py
from flask import url_for, redirect, Blueprint
from flask_login import login_required
from flask_security import current_user
from beebloge import db
from beebloge.models import BlogPost, Comment, Product

comments = Blueprint('comments', __name__)


@comments.route('/comment/<int:comment_id>/<int:postProductId>/delete', methods=["POST"])
@login_required
def delete_comment(postProductId, comment_id):
    comment = Comment.query.get_or_404(comment_id)

    if comment.author == current_user or current_user.has_role('admin'):
        db.session.delete(comment)
        db.session.commit()
        # flash('Comment has been deleted')
        if comment.post_id:
            blog_post = BlogPost.query.get_or_404(postProductId)
            return redirect(url_for('blogPosts.blog_post', blog_post_id=blog_post.id))
        if comment.product_id:
            product = Product.query.get_or_404(postProductId)
            return redirect(url_for('products.product', product_id=product.id))
    else:
        abort(403)

beebloge/core/views.py
from flask import render_template, request, Blueprint, redirect
from beebloge.models import BlogPost

core = Blueprint('core', __name__)


@core.route('/index')
def indexRedirect():
    return redirect('/')


@core.route('/')
def index():
    '''
    This is the home page view. Use pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=100)
    return render_template('index.html', blog_posts=blog_posts)


@core.route('/info')
def info():
    '''
    Example view of any other "core" page.
    '''
    return render_template('info.html')

beebloge/products/views.py
from flask import render_template, url_for, redirect, request, Blueprint, flash
from flask_login import login_required
from flask_security import current_user

from beebloge import db
from beebloge.comments.forms import CommentForm
from beebloge.models import Comment, Product
from beebloge.products.forms import ProductForm
from beebloge.users.picture_handler import add_pic, del_pic
from beebloge.users.views import requires_roles
import urllib.parse

products = Blueprint('products', __name__)


@products.route('/create/product', methods=['GET', 'POST'])
@login_required
@requires_roles('admin')
def create_product():
    form = ProductForm()

    if form.validate_on_submit() and form.check_title():

        if form.picture.data:
            imgname = "".join([form.title.data[:20], form.category.data])
            pic = add_pic(form.picture.data, imgname, 'product_pics', (450, 600))

            Product(title           =form.title.data,
                    text            =form.text.data,
                    short_text      =form.shortText.data,
                    category        =form.category.data,
                    user_id         =current_user.id,
                    product_image   =pic)

            flash("Blog Post Created")
            return redirect(url_for('core.index'))

    return render_template('addProduct.html', form=form)


@products.route('/product/<int:product_id>', strict_slashes=False, methods=["GET", "POST"])
def product(product_id):
    # grab the requested blog post by id number or return 404
    product = Product.query.get_or_404(product_id)
    form = CommentForm()
    if form.validate_on_submit():
        Comment(body        =form.comment.data,
                post_id     ='',
                product_id  =product.id,
                user_id     =current_user.id)

        # flash("Your comments has been added to the post", "success")

    return render_template('product.html',
                           title        =product.title,
                           date         =product.date,
                           product      =product,
                           category     =product.category,
                           product_image=product.product_image,
                           form         =form)


@products.route('/product/<int:product_id>/update', methods=['GET', 'POST'])
@login_required
def update(product_id):
    product = Product.query.get_or_404(product_id)
    if product.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = ProductForm()

    if form.validate_on_submit():
        if form.picture.data:
            imgname = "".join([form.title.data[:20], form.category.data])
            del_pic(fileName=product.product_image)
            pic = add_pic(form.picture.data, imgname, 'product_pics', (450, 600))
            product.post_image = pic

        product.title       = form.title.data
        product.text        = form.text.data
        product.category    = form.category.data
        product.short_text  = form.shortText.data

        db.session.commit()
        # flash('Post Updated')
        return redirect(url_for('products.products_list', product_id=product.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data     = product.title
        form.text.data      = product.text
        form.shortText.data = product.short_text
        form.category.data  = product.category
        form.picture.data   = product.product_image

    return render_template('addProduct.html', title='Update',
                           form=form)


@products.route('/product/<int:product_id>/delete', methods=['POST'])
@login_required
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)
    if product.author != current_user:
        abort(403)
    del_pic(fileName=product.product_image)
    db.session.delete(product)
    db.session.commit()
    # flash('Post has been deleted')
    return redirect(url_for('products.products_list'))


@products.route('/product/list')
def products_list():
    '''
    This is the home page view. Use pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    categories = Product.get_category_list()
    products = Product.get_products_list()

    return render_template('productList.html', products=products, categories=categories)


@products.route('/product/list/filter/<string:query>', methods=['POST', 'GET'])
def products_list_filter(query):
    categories = Product.get_category_list()
    products = Product.find_by_category(urllib.parse.unquote(query))
    return render_template('productList.html', products=products, categories=categories)

beebloge/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, logout_user, login_required
from beebloge import db
from beebloge.models import User, BlogPost, Product, Role
from beebloge.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from beebloge.users.picture_handler import add_pic
from flask_admin.contrib.sqla import ModelView
from flask_admin import AdminIndexView, expose
from functools import wraps
from flask_security import SQLAlchemySessionUserDatastore, current_user
from flask_security.utils import hash_password

user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)
users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit() and form.check_email() and form.check_username():
        role = user_datastore.find_or_create_role(name='user', description='FOLLOW | COMMENT')

        user = user_datastore.create_user(email         =form.email.data,
                                          first_name    =form.username.data,
                                          password      =hash_password(form.password.data))

        user_datastore.add_role_to_user(user, role)
        db.session.commit()

        # flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = user_datastore.get_user(form.email.data)
        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            # Log in the user

            login_user(user)
            flash('Jesteś zalogowany!')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)
        else:
            flash('Błędne hasło!')

    return render_template('security\login_user.html', login_user_form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():

        current_user.first_name = form.username.data
        current_user.email = form.email.data
        user = user_datastore.get_user(current_user.email)
        user.password = hash_password(form.password.data)
        if form.picture.data:
            username = current_user.first_name
            pic = add_pic(form.picture.data, username, 'profile_pics', (800, 800))
            current_user.profile_image = pic
        db.session.commit()

        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.first_name
        form.email.data    = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(first_name=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('userBlogPosts.html', blog_posts=blog_posts, user=user)


# </editor-fold>


@users.route('/<username>')
def user_products(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(first_name=username).first_or_404()
    products = Product.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('userProducts.html', products=products, user=user)


# </editor-fold>


# Create a ModelView to add to our administrative interface
class MyAdminIndexView(AdminIndexView):

    @expose('/')
    def index(self):
        if not current_user.is_authenticated:
            return redirect(url_for('/login'))
        return super(MyAdminIndexView, self).index()

    def is_accessible(self):
        return (current_user.is_active and
                current_user.is_authenticated and current_user.has_role('admin'))

    def _handle_view(self, name):
        if not self.is_accessible():
            if current_user.is_authenticated:
                abort(403)
            return redirect(url_for('users.login'))


# Create a ModelView to add to our administrative interface
class MyModelView(ModelView):
    def is_accessible(self):
        return (current_user.is_active and
                current_user.is_authenticated and current_user.has_role('admin'))

    def _handle_view(self, name):
        if not self.is_accessible():
            if current_user.is_authenticated:
                abort(403)
            return redirect(url_for('users.login'))

    column_list = ['email', 'password']


def requires_roles(*roles):
    def wrapper(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            for role in roles:
                if current_user.has_role(role):
                    # Redirect the user to an unauthorized notice!
                    return f(*args, **kwargs)

            return "You are not authorized to access this page"

        return wrapped

    return wrapper

beebloge/templates/add_product.html
{% extends "base.html" %}
	{%import "bootstrap/wtf.html" as wtf%}
	{% block content %}


	<div id="fh5co-content" class="fh5co-no-pd-top">
		<div class="container">

			<div class="row animate-box">
				<div class="col-md-12 col-md-offset-0 text-center fh5co-heading">
					<h2><span>Nowy Produkt</span></h2>
				</div>
			</div>

			<div class="row">


				<div class="col-md-9 col-padded-right">
					<div class="row">

						<div class="container">
							<form class="form-group row" method="POST" action="" enctype="multipart/form-data">
								{{ form.hidden_tag() }}

								<div class="col-xs-9">
									{{wtf.form_field(form.title, class="form-control")}}
								</div>
								<div class="col-xs-9">
									{{wtf.form_field(form.category, class="form-control",rows="20")}}
								</div>
								<div class="col-xs-9">
									{{wtf.form_field(form.text, class="form-control")}}
								</div>
								<div class="col-xs-9" style="float: left; width: 300px">
									{{wtf.form_field(form.picture, class="form-control-file")}}
								</div>

								<div class="col-xs-9" style="float: right; width: 420px">
									{{ form.submit(class="btn btn-outline-info",style="height:50px;width:100px") }}
								</div>

								{
							</form>
							{{ ckeditor.load() }}
							{{ ckeditor.config(name='text') }}
						</div>


					</div>
				</div>


				<div class="col-md-3">
					<div class="side animate-box">
						<div class="col-md-12 col-md-offset-0 text-center fh5co-heading fh5co-heading-sidebar">
							<h2><span>O Mnie</span></h2>
						</div>
						<div class="fh5co-staff">
							<img src="static/profile_pics/Maria.jpg">
							<h3>Maria Mucha</h3>
							<strong class="role">Założyciel bloga</strong>
							<p href="{{ url_for('core.info') }}">Mam na imię Maria i jestem studentką Technologii
								Chemicznej na PW. Moją największą pasją jest wspinaczka i od jakiegoś czasu wszystko co
								jest związane z pszczołami, stąd pomysł na stworzenie tego bloga. :)</p>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>


	{% endblock content %}

beebloge/templates/base.html
<!DOCTYPE html>
	<html lang="pl">
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Bee Bloge - roztanczonwa pszczolka</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Personal blog about bees, creams and cosmetics" />
		<meta name="language" content="Polish" />
		<meta name="keywords" content="Blog , creams, cosmetics, bees, personal blog, students, chemistry, kombucha, krem galonowy, krem,kosmetyki
		, student, chemia, pszczoły " />
		<meta name="author" content="https://github.com/markoseb" />

		<!-- Icomoon Icon Fonts-->
		<link rel="stylesheet" href="/static/css/icomoon.css">
		<link rel="stylesheet" href="/static/css/bootstrap.css">
			<!-- Theme style  -->
		<link rel="stylesheet" href="/static/css/style.css">

		<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,300&family=Dancing+Script&family=Sacramento&display=swap"
			  rel="stylesheet">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Amatic+SC&display=swap" rel="stylesheet">

		<!-- Animate.css -->
		<link rel="stylesheet" href="/static/css/animate.css">

		<!-- Magnific Popup -->
		<link rel="stylesheet" href="/static/css/magnific-popup.css">

		<!-- Flexslider  -->
		<link rel="stylesheet" href="/static/css/flexslider.css">

		<link rel="shortcut icon" type="image/png" href="/static/pics/32icon.png">

		<!-- Modernizr JS -->
		<script src="/static/js/modernizr-2.6.2.min.js"></script>
		<!-- FOR IE9 below -->
		<!--[if lt IE 9]>
		<script src="/static/js/respond.min.js"></script>
		<![endif]-->


		<script  src="/static/js/ckeditor/ckeditor.js"></script>


	</head>
	<body>
	<div class="fh5co-loader"></div>
	<div id="page">
		<nav class="fh5co-nav" >
			<div class="container-fluid">
				<div class="row">
					<div class="top-menu">
						<div class="container">
							<div class="row">
								<div class="col-sm-9 text-left menu-1" >
									<ul>
										<li class="active"><a href="{{ url_for('core.index') }}">Strona główna</a></li>
										<li><a href="{{ url_for('products.products_list') }}">Rękodzieła</a></li>
										<li><a href="{{ url_for('core.info') }}">O mnie</a></li>
										{% if current_user.is_authenticated %}
										<li><a href="{{ url_for('users.logout') }}">Wyloguj się</a></li>
										<li><a href="{{ url_for('users.account') }}">Konto</a></li>
										{% if current_user.has_role('admin') %}
										<li><a href="{{ url_for('blogPosts.create_post') }}">Nowy Post</a></li>
										<li><a href="{{ url_for('products.create_product') }}">Nowy Produkt</a></li>
										{% endif %}
										{% else %}
										<li><a href="{{ url_for('users.login') }}">Zaloguj się</a></li>
										<li><a href="{{ url_for('users.register') }}">Rejestracja</a></li>
										{% endif %}
									</ul>
								</div>
										<div class="col-sm-3">
											<div class="fh5co-social-icons">
												<ul>
													<li><a href="https://www.facebook.com/maria.wiedenska5"><i class="icon-facebook-with-circle"></i></a></li>
													<li><a href="https://www.instagram.com/maria_muszka/"><i class="icon-instagram-with-circle"></i></a></li>
												</ul>
											</div>
										</div>
							</div>

						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 text-center menu-2">
						<div id="fh5co-logo">
							<a href="{{ url_for('core.index') }}">
								<img id="logo" src="/static/pics/logo.png" alt="Bee logo">
							</a>
						</div>
					</div>
				</div>
			</div>
		</nav>


		<div class="container">
			{% block content %}

			{% endblock %}
		</div>


		<footer id="fh5co-footer" >

				<p>


				</p>

				<div class="row row-pb-md">

					<div class="col-md-3 col-md-push-1">
						<ul class="fh5co-footer-links">

							<li><a href="{{ url_for('core.index') }}"><img src="/static/pics/headerlogo.png" alt="Header logo"></a></li>
							<li><h1  data-url_root="{{ url_for('core.index') }}">Roztańczona Pszczółka</h1></li>
						</ul>
					</div>

					<div class="col-md-3 col-md-push-1">

						<ul class="fh5co-footer-links">
							<li><h4>Links</h4></li>
							<li><a href="{{ url_for('core.index') }}">Strona Główna</a></li>
							<li><a href="{{ url_for('core.info') }}">O mnie</a></li>
							<li><a href="{{ url_for('users.account') }}">Konto</a></li>
						</ul>
					</div>

					<div class="col-md-3 col-md-push-1">

						<ul class="fh5co-footer-links">
							<li><h4>Kontakt</h4></li>
							<li><a href="tel://">+48 691 365 852</a></li>
							<li><a href="mailto:info@yoursite.com">http://roztanczonapszczolka.pl/</a></li>
							<li><a href="">Web site</a></li>
						</ul>
					</div>
					<div class="col-md-3 col-md-push-1">
						<div class="fh5co-social-icons icons-footer" >
							<ul class="fh5co-footer-links">
								<li><a href="https://www.facebook.com/maria.wiedenska5"><i class="icon-facebook-with-circle"></i></a></li>
								<li><a href="https://www.instagram.com/maria_muszka/"><i class="icon-instagram-with-circle"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="row copyright">
					<div class="col-md-12 text-center">
						<p>
							<small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small>
							<small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a>
								Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
							<small class="block">Changed by <a href="https://github.com/markoseb"
															   target="_blank">Markoseb</a> </small>
						</p>

					</div>
				</div>


		</footer>

	</div>


	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	<!-- jQuery -->
	<script src="/static/js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="/static/js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="/static/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="/static/js/jquery.waypoints.min.js"></script>
	<!-- Flexslider -->
	<script src="/static/js/jquery.flexslider-min.js"></script>
	<!-- Magnific Popup -->
	<script src="/static/js/jquery.magnific-popup.min.js"></script>
	<script src="/static/js/magnific-popup-options.js"></script>
	<!-- Main -->
	<script src="/static/js/main.js"></script>
	</body>
	</html>

beebloge/templates/blogPost.html
{% extends "base.html" %}
  {%import "bootstrap/wtf.html" as wtf%}
  {% block content %}
  <div class="jumbotron">
    <h1>{{ post.title }}</h1>
    <h2>Autor: {{post.author.first_name}}</h2>
    <h2>Kategoria: {{post.category}}</h2>
    <h3>Opublikowano: {{ post.date.strftime('%B %d, %Y') }}</h3>
    {{ post.text|safe|urlize }}


  </div>
  {% if post.author == current_user and current_user.has_role('admin') %}
  <div style="margin-bottom: 30px;">
    <a class="btn btn-primary" href="{{ url_for('blogPosts.update', blog_post_id=post.id) }}">Edytuj</a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Usuń</button>
  </div>
  {% endif %}

  <form class="form-group row" method="POST" >
    {{ form.hidden_tag() }}
    {{form.comment.label(style="margin-left: 1vw")}}
    {{form.comment(class="new-comment",style="margin-left: 1vw;margin-bottom: 1em;width: 98%")}}
    {% if current_user.is_authenticated %}
    {{ form.submit(class="btn btn-primary",style="margin-left: 1vw;margin-bottom: 3em;") }}
    {% else %}
    <p style="margin-left: 1vw;margin-bottom: 6em;">Zaloguj się i dodaj komentarz!</p>
    {% endif %}
  </form>


  {% if post.comments %}
  {% if post.comments.count() > 0 %}
  <h2>Komentarze</h2>

  <p>
    {% for comment in post.comments %}
  <p>{{ comment.author.first_name }} : {{ comment.date.strftime('%X - %B %d, %Y') }}</p>
  <div class="jumbotron">
    {% if comment.author == current_user or current_user.has_role('admin') %}
    <form action="{{ url_for('comments.delete_comment',  postProductId=post.id , comment_id=comment.id) }}"
          method="POST">
      <button type="submit" class="btn btn-light" style="margin: -75px 0 0 1020px"><i class="icon-delete"
                                                                                      aria-hidden="true"></i></button>
    </form>
    {% endif %}
    <p type="text" readonly="readonly"/>{{ comment.body }}</p>
  </div>

  {% endfor %}

  </p>
  {% endif %}
  {% endif %}


  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blogPosts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>


  {% endblock content %}

beebloge/templates/userBlogPosts.html
{% extends "base.html" %}
    {% block content %}
    <div class="container">
        <div class="jumbotron">
            <div align='center'>
                <h1>Welcome to the page for {{user.username}}</h1>
                <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
            </div>
        </div>


        {% for post in blog_posts.items %}

        <h2><a href="{{ url_for('blogPosts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
        }}</a>
        <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <img class="img-responsive" src="{{ url_for('static', filename='post_pics/' + blog_posts.post_image) }}" alt="">
        <p>{{post.post_image|safe}}</p>
        <br>
        <p>{{post.text}}</p>
        <br>

        {% endfor %}


    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {# http://flask.pocoo.org/snippets/44/ #}

            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
            <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
                    page_num }}</a></li>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link"
                                     href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
                page_num }}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
    {% endblock content %}